# Site config
baseurl: ""

# User config
author: "Tien Dinh"
description: "A Personal Portfolio."
email: "tiendinhphuc@gmail.com"

# User collections
collections:
    projects:
        output: true

# Collection defaults.
defaults:
-
    scope:
        path: "_posts"
        type: "posts"
    values:
        layout: page
-
    scope:
        path: "_project"
        type: "project"
    values:
        layout: page
        image: /assets/img/placeholder.jpg
